# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76187bbf679ef3939e0d11ca673064e8244ed5eb975f66365c6a867d2d532b64c72c651ae524e89f61974a19acee2c352f5ebba1fbb6790ceba406416c4ab910

test:
  secret_key_base: 23a787bcbb077599ae5fcdf0a1b8525f06402ac3e6cb84de07c7164394df839ceec4bb3c44e07335e7321b9a824875fc45c9624423f67bdda098b2514fc6d5d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
